[2017-09-19 15:21:25 +0800] [11216] [INFO] Starting gunicorn 19.7.1
[2017-09-19 15:21:25 +0800] [11216] [INFO] Listening at: http://127.0.0.1:8082 (11216)
[2017-09-19 15:21:25 +0800] [11216] [INFO] Using worker: gevent
[2017-09-19 15:21:25 +0800] [11219] [INFO] Booting worker with pid: 11219
[2017-09-19 15:21:25 +0800] [11220] [INFO] Booting worker with pid: 11220
[2017-09-19 15:21:25 +0800] [11221] [INFO] Booting worker with pid: 11221
[2017-09-19 15:21:25 +0800] [11222] [INFO] Booting worker with pid: 11222
[2017-09-19 15:47:25 +0800] [11216] [INFO] Handling signal: term
[2017-09-19 15:47:25 +0800] [11221] [INFO] Worker exiting (pid: 11221)
[2017-09-19 15:47:25 +0800] [11222] [INFO] Worker exiting (pid: 11222)
[2017-09-19 15:47:26 +0800] [11220] [INFO] Worker exiting (pid: 11220)
[2017-09-19 15:47:26 +0800] [11219] [INFO] Worker exiting (pid: 11219)
[2017-09-19 15:47:26 +0800] [11216] [INFO] Shutting down: Master
[2017-09-19 15:47:27 +0800] [14817] [INFO] Starting gunicorn 19.7.1
[2017-09-19 15:47:27 +0800] [14817] [INFO] Listening at: http://127.0.0.1:8082 (14817)
[2017-09-19 15:47:27 +0800] [14817] [INFO] Using worker: gevent
[2017-09-19 15:47:27 +0800] [14820] [INFO] Booting worker with pid: 14820
[2017-09-19 15:47:27 +0800] [14821] [INFO] Booting worker with pid: 14821
[2017-09-19 15:47:27 +0800] [14822] [INFO] Booting worker with pid: 14822
[2017-09-19 15:47:27 +0800] [14823] [INFO] Booting worker with pid: 14823
[2017-09-19 15:52:47 +0800] [14817] [INFO] Handling signal: term
[2017-09-19 15:52:47 +0800] [14820] [INFO] Worker exiting (pid: 14820)
[2017-09-19 15:52:47 +0800] [14821] [INFO] Worker exiting (pid: 14821)
[2017-09-19 15:52:48 +0800] [14822] [INFO] Worker exiting (pid: 14822)
[2017-09-19 15:52:48 +0800] [14823] [INFO] Worker exiting (pid: 14823)
[2017-09-19 15:52:48 +0800] [14817] [INFO] Shutting down: Master
[2017-09-19 15:52:48 +0800] [15608] [INFO] Starting gunicorn 19.7.1
[2017-09-19 15:52:48 +0800] [15608] [INFO] Listening at: http://127.0.0.1:8082 (15608)
[2017-09-19 15:52:48 +0800] [15608] [INFO] Using worker: gevent
[2017-09-19 15:52:48 +0800] [15611] [INFO] Booting worker with pid: 15611
[2017-09-19 15:52:48 +0800] [15612] [INFO] Booting worker with pid: 15612
[2017-09-19 15:52:48 +0800] [15613] [INFO] Booting worker with pid: 15613
[2017-09-19 15:52:48 +0800] [15614] [INFO] Booting worker with pid: 15614
[2017-09-19 19:08:55 +0800] [15608] [INFO] Handling signal: term
[2017-09-19 19:08:55 +0800] [15613] [INFO] Worker exiting (pid: 15613)
[2017-09-19 19:08:55 +0800] [15612] [INFO] Worker exiting (pid: 15612)
[2017-09-19 19:08:55 +0800] [15614] [INFO] Worker exiting (pid: 15614)
[2017-09-19 19:08:55 +0800] [15611] [INFO] Worker exiting (pid: 15611)
[2017-09-19 19:08:55 +0800] [15608] [INFO] Shutting down: Master
[2017-09-19 19:08:56 +0800] [28807] [INFO] Starting gunicorn 19.7.1
[2017-09-19 19:08:56 +0800] [28807] [INFO] Listening at: http://127.0.0.1:8082 (28807)
[2017-09-19 19:08:56 +0800] [28807] [INFO] Using worker: gevent
[2017-09-19 19:08:56 +0800] [28810] [INFO] Booting worker with pid: 28810
[2017-09-19 19:08:56 +0800] [28812] [INFO] Booting worker with pid: 28812
[2017-09-19 19:08:56 +0800] [28813] [INFO] Booting worker with pid: 28813
[2017-09-19 19:08:56 +0800] [28814] [INFO] Booting worker with pid: 28814
[2017-09-19 20:17:42 +0800] [28807] [INFO] Handling signal: term
[2017-09-19 20:17:42 +0800] [28812] [INFO] Worker exiting (pid: 28812)
[2017-09-19 20:17:43 +0800] [28810] [INFO] Worker exiting (pid: 28810)
[2017-09-19 20:17:43 +0800] [28814] [INFO] Worker exiting (pid: 28814)
[2017-09-19 20:17:43 +0800] [28813] [INFO] Worker exiting (pid: 28813)
[2017-09-19 20:17:43 +0800] [28807] [INFO] Shutting down: Master
[2017-09-19 20:17:43 +0800] [5244] [INFO] Starting gunicorn 19.7.1
[2017-09-19 20:17:43 +0800] [5244] [INFO] Listening at: http://127.0.0.1:8082 (5244)
[2017-09-19 20:17:43 +0800] [5244] [INFO] Using worker: gevent
[2017-09-19 20:17:43 +0800] [5247] [INFO] Booting worker with pid: 5247
[2017-09-19 20:17:43 +0800] [5248] [INFO] Booting worker with pid: 5248
[2017-09-19 20:17:43 +0800] [5249] [INFO] Booting worker with pid: 5249
[2017-09-19 20:17:44 +0800] [5250] [INFO] Booting worker with pid: 5250
[2017-09-19 20:28:58 +0800] [5244] [INFO] Handling signal: term
[2017-09-19 20:28:58 +0800] [5247] [INFO] Worker exiting (pid: 5247)
[2017-09-19 20:28:58 +0800] [5248] [INFO] Worker exiting (pid: 5248)
[2017-09-19 20:28:58 +0800] [5249] [INFO] Worker exiting (pid: 5249)
[2017-09-19 20:28:58 +0800] [5250] [INFO] Worker exiting (pid: 5250)
[2017-09-19 20:28:58 +0800] [5244] [INFO] Shutting down: Master
[2017-09-19 20:28:59 +0800] [7907] [INFO] Starting gunicorn 19.7.1
[2017-09-19 20:28:59 +0800] [7907] [INFO] Listening at: http://127.0.0.1:8082 (7907)
[2017-09-19 20:28:59 +0800] [7907] [INFO] Using worker: gevent
[2017-09-19 20:28:59 +0800] [7910] [INFO] Booting worker with pid: 7910
[2017-09-19 20:28:59 +0800] [7911] [INFO] Booting worker with pid: 7911
[2017-09-19 20:28:59 +0800] [7912] [INFO] Booting worker with pid: 7912
[2017-09-19 20:28:59 +0800] [7913] [INFO] Booting worker with pid: 7913
WARNING|2017-09-19 20:29:12|7910|140575812361104|server.py:41|WARN
[2017-09-19 20:29:12,744] ERROR in server: ERROR
ERROR|2017-09-19 20:29:12|7910|140575812361104|server.py:42|ERROR
[2017-09-19 20:31:27 +0800] [7907] [INFO] Handling signal: term
[2017-09-19 20:31:28 +0800] [7911] [INFO] Worker exiting (pid: 7911)
[2017-09-19 20:31:28 +0800] [7912] [INFO] Worker exiting (pid: 7912)
[2017-09-19 20:31:28 +0800] [7910] [INFO] Worker exiting (pid: 7910)
[2017-09-19 20:31:28 +0800] [7913] [INFO] Worker exiting (pid: 7913)
[2017-09-19 20:31:28 +0800] [7907] [INFO] Shutting down: Master
[2017-09-19 20:31:28 +0800] [8306] [INFO] Starting gunicorn 19.7.1
[2017-09-19 20:31:28 +0800] [8306] [INFO] Listening at: http://127.0.0.1:8082 (8306)
[2017-09-19 20:31:28 +0800] [8306] [INFO] Using worker: gevent
[2017-09-19 20:31:28 +0800] [8309] [INFO] Booting worker with pid: 8309
[2017-09-19 20:31:28 +0800] [8310] [INFO] Booting worker with pid: 8310
[2017-09-19 20:31:28 +0800] [8311] [INFO] Booting worker with pid: 8311
[2017-09-19 20:31:28 +0800] [8312] [INFO] Booting worker with pid: 8312
[2017-09-19 20:31:51,189] ERROR in server: ERROR
[2017-09-19 21:03:05 +0800] [8306] [INFO] Handling signal: term
[2017-09-19 21:03:06 +0800] [8309] [INFO] Worker exiting (pid: 8309)
[2017-09-19 21:03:06 +0800] [8310] [INFO] Worker exiting (pid: 8310)
[2017-09-19 21:03:06 +0800] [8311] [INFO] Worker exiting (pid: 8311)
[2017-09-19 21:03:06 +0800] [8312] [INFO] Worker exiting (pid: 8312)
[2017-09-19 21:03:06 +0800] [8306] [INFO] Shutting down: Master
[2017-09-19 21:03:07 +0800] [20145] [INFO] Starting gunicorn 19.7.1
[2017-09-19 21:03:07 +0800] [20145] [INFO] Listening at: http://127.0.0.1:8082 (20145)
[2017-09-19 21:03:07 +0800] [20145] [INFO] Using worker: gevent
[2017-09-19 21:03:07 +0800] [20148] [INFO] Booting worker with pid: 20148
[2017-09-19 21:03:07 +0800] [20149] [INFO] Booting worker with pid: 20149
[2017-09-19 21:03:07 +0800] [20150] [INFO] Booting worker with pid: 20150
[2017-09-19 21:03:07 +0800] [20151] [INFO] Booting worker with pid: 20151
[2017-09-19 21:05:32,496] ERROR in server: ERROR
[2017-09-19 21:09:28 +0800] [20145] [INFO] Handling signal: term
[2017-09-19 21:09:29 +0800] [20149] [INFO] Worker exiting (pid: 20149)
[2017-09-19 21:09:29 +0800] [20148] [INFO] Worker exiting (pid: 20148)
[2017-09-19 21:09:29 +0800] [20151] [INFO] Worker exiting (pid: 20151)
[2017-09-19 21:09:29 +0800] [20150] [INFO] Worker exiting (pid: 20150)
[2017-09-19 21:09:29 +0800] [20145] [INFO] Shutting down: Master
[2017-09-19 21:09:29 +0800] [20982] [INFO] Starting gunicorn 19.7.1
[2017-09-19 21:09:29 +0800] [20982] [INFO] Listening at: http://127.0.0.1:8082 (20982)
[2017-09-19 21:09:29 +0800] [20982] [INFO] Using worker: gevent
[2017-09-19 21:09:29 +0800] [20985] [INFO] Booting worker with pid: 20985
[2017-09-19 21:09:29 +0800] [20986] [INFO] Booting worker with pid: 20986
[2017-09-19 21:09:29 +0800] [20987] [INFO] Booting worker with pid: 20987
[2017-09-19 21:09:29 +0800] [20988] [INFO] Booting worker with pid: 20988
[2017-09-19 21:09:37,893] ERROR in server: ERROR
[2017-09-19 21:12:33 +0800] [20982] [INFO] Handling signal: term
[2017-09-19 21:12:34 +0800] [20986] [INFO] Worker exiting (pid: 20986)
[2017-09-19 21:12:34 +0800] [20985] [INFO] Worker exiting (pid: 20985)
[2017-09-19 21:12:34 +0800] [20988] [INFO] Worker exiting (pid: 20988)
[2017-09-19 21:12:34 +0800] [20987] [INFO] Worker exiting (pid: 20987)
[2017-09-19 21:12:34 +0800] [20982] [INFO] Shutting down: Master
[2017-09-19 21:12:35 +0800] [21449] [INFO] Starting gunicorn 19.7.1
[2017-09-19 21:12:35 +0800] [21449] [INFO] Listening at: http://127.0.0.1:8082 (21449)
[2017-09-19 21:12:35 +0800] [21449] [INFO] Using worker: gevent
[2017-09-19 21:12:35 +0800] [21452] [INFO] Booting worker with pid: 21452
[2017-09-19 21:12:35 +0800] [21453] [INFO] Booting worker with pid: 21453
[2017-09-19 21:12:35 +0800] [21454] [INFO] Booting worker with pid: 21454
[2017-09-19 21:12:35 +0800] [21455] [INFO] Booting worker with pid: 21455
[2017-09-19 21:12:48,607] ERROR in server: ERROR
[2017-09-19 21:13:45 +0800] [21449] [INFO] Handling signal: term
[2017-09-19 21:13:45 +0800] [21454] [INFO] Worker exiting (pid: 21454)
[2017-09-19 21:13:45 +0800] [21453] [INFO] Worker exiting (pid: 21453)
[2017-09-19 21:13:45 +0800] [21455] [INFO] Worker exiting (pid: 21455)
[2017-09-19 21:13:46 +0800] [21452] [INFO] Worker exiting (pid: 21452)
[2017-09-19 21:13:46 +0800] [21449] [INFO] Shutting down: Master
[2017-09-19 21:13:47 +0800] [21539] [INFO] Starting gunicorn 19.7.1
[2017-09-19 21:13:47 +0800] [21539] [INFO] Listening at: http://127.0.0.1:8082 (21539)
[2017-09-19 21:13:47 +0800] [21539] [INFO] Using worker: gevent
[2017-09-19 21:13:47 +0800] [21542] [INFO] Booting worker with pid: 21542
[2017-09-19 21:13:47 +0800] [21543] [INFO] Booting worker with pid: 21543
[2017-09-19 21:13:47 +0800] [21544] [INFO] Booting worker with pid: 21544
[2017-09-19 21:13:47 +0800] [21545] [INFO] Booting worker with pid: 21545
[2017-09-19 21:13:51,488] ERROR in server: ERROR
[2017-09-19 22:08:44 +0800] [21539] [INFO] Handling signal: term
[2017-09-19 22:08:45 +0800] [21543] [INFO] Worker exiting (pid: 21543)
[2017-09-19 22:08:45 +0800] [21542] [INFO] Worker exiting (pid: 21542)
[2017-09-19 22:08:45 +0800] [21544] [INFO] Worker exiting (pid: 21544)
[2017-09-19 22:08:45 +0800] [21545] [INFO] Worker exiting (pid: 21545)
[2017-09-19 22:08:45 +0800] [21539] [INFO] Shutting down: Master
[2017-09-19 22:08:45 +0800] [31062] [INFO] Starting gunicorn 19.7.1
[2017-09-19 22:08:45 +0800] [31062] [INFO] Listening at: http://127.0.0.1:8082 (31062)
[2017-09-19 22:08:45 +0800] [31062] [INFO] Using worker: gevent
[2017-09-19 22:08:45 +0800] [31065] [INFO] Booting worker with pid: 31065
[2017-09-19 22:08:45 +0800] [31066] [INFO] Booting worker with pid: 31066
[2017-09-19 22:08:45 +0800] [31067] [INFO] Booting worker with pid: 31067
[2017-09-19 22:08:45 +0800] [31068] [INFO] Booting worker with pid: 31068
[2017-09-19 22:09:02,493] ERROR in server: ERROR
[2017-09-19 22:33:15 +0800] [31062] [INFO] Handling signal: term
[2017-09-19 22:33:15 +0800] [31066] [INFO] Worker exiting (pid: 31066)
[2017-09-19 22:33:15 +0800] [31065] [INFO] Worker exiting (pid: 31065)
[2017-09-19 22:33:15 +0800] [31067] [INFO] Worker exiting (pid: 31067)
[2017-09-19 22:33:16 +0800] [31068] [INFO] Worker exiting (pid: 31068)
[2017-09-19 22:33:16 +0800] [31062] [INFO] Shutting down: Master
[2017-09-19 22:33:16 +0800] [3773] [INFO] Starting gunicorn 19.7.1
[2017-09-19 22:33:16 +0800] [3773] [INFO] Listening at: http://127.0.0.1:8082 (3773)
[2017-09-19 22:33:16 +0800] [3773] [INFO] Using worker: gevent
[2017-09-19 22:33:16 +0800] [3776] [INFO] Booting worker with pid: 3776
[2017-09-19 22:33:16 +0800] [3777] [INFO] Booting worker with pid: 3777
[2017-09-19 22:33:16 +0800] [3778] [INFO] Booting worker with pid: 3778
[2017-09-19 22:33:16 +0800] [3779] [INFO] Booting worker with pid: 3779
WARNING
ERROR
[2017-09-19 22:35:02 +0800] [3773] [INFO] Handling signal: term
[2017-09-19 22:35:03 +0800] [3776] [INFO] Worker exiting (pid: 3776)
[2017-09-19 22:35:03 +0800] [3777] [INFO] Worker exiting (pid: 3777)
[2017-09-19 22:35:03 +0800] [3778] [INFO] Worker exiting (pid: 3778)
[2017-09-19 22:35:03 +0800] [3779] [INFO] Worker exiting (pid: 3779)
[2017-09-19 22:35:03 +0800] [3773] [INFO] Shutting down: Master
[2017-09-19 22:35:03 +0800] [4039] [INFO] Starting gunicorn 19.7.1
[2017-09-19 22:35:03 +0800] [4039] [INFO] Listening at: http://127.0.0.1:8082 (4039)
[2017-09-19 22:35:03 +0800] [4039] [INFO] Using worker: gevent
[2017-09-19 22:35:03 +0800] [4042] [INFO] Booting worker with pid: 4042
[2017-09-19 22:35:03 +0800] [4043] [INFO] Booting worker with pid: 4043
[2017-09-19 22:35:03 +0800] [4044] [INFO] Booting worker with pid: 4044
[2017-09-19 22:35:03 +0800] [4045] [INFO] Booting worker with pid: 4045
[2017-09-19 22:36:37 +0800] [4039] [INFO] Handling signal: term
[2017-09-19 22:36:37 +0800] [4043] [INFO] Worker exiting (pid: 4043)
[2017-09-19 22:36:37 +0800] [4044] [INFO] Worker exiting (pid: 4044)
[2017-09-19 22:36:37 +0800] [4045] [INFO] Worker exiting (pid: 4045)
[2017-09-19 22:36:38 +0800] [4042] [INFO] Worker exiting (pid: 4042)
[2017-09-19 22:36:38 +0800] [4039] [INFO] Shutting down: Master
[2017-09-19 22:36:38 +0800] [4245] [INFO] Starting gunicorn 19.7.1
[2017-09-19 22:36:38 +0800] [4245] [INFO] Listening at: http://127.0.0.1:8082 (4245)
[2017-09-19 22:36:38 +0800] [4245] [INFO] Using worker: gevent
[2017-09-19 22:36:38 +0800] [4248] [INFO] Booting worker with pid: 4248
[2017-09-19 22:36:38 +0800] [4249] [INFO] Booting worker with pid: 4249
[2017-09-19 22:36:38 +0800] [4250] [INFO] Booting worker with pid: 4250
[2017-09-19 22:36:38 +0800] [4251] [INFO] Booting worker with pid: 4251
[2017-09-20 09:43:32 +0800] [4245] [INFO] Handling signal: term
[2017-09-20 09:43:32 +0800] [4248] [INFO] Worker exiting (pid: 4248)
[2017-09-20 09:43:32 +0800] [4251] [INFO] Worker exiting (pid: 4251)
[2017-09-20 09:43:32 +0800] [4250] [INFO] Worker exiting (pid: 4250)
[2017-09-20 09:43:32 +0800] [4249] [INFO] Worker exiting (pid: 4249)
[2017-09-20 09:43:32 +0800] [4245] [INFO] Shutting down: Master
[2017-09-20 09:43:33 +0800] [27010] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:43:33 +0800] [27010] [INFO] Listening at: http://127.0.0.1:8082 (27010)
[2017-09-20 09:43:33 +0800] [27010] [INFO] Using worker: gevent
[2017-09-20 09:43:33 +0800] [27013] [INFO] Booting worker with pid: 27013
[2017-09-20 09:43:33 +0800] [27014] [INFO] Booting worker with pid: 27014
[2017-09-20 09:43:33 +0800] [27015] [INFO] Booting worker with pid: 27015
[2017-09-20 09:43:33 +0800] [27016] [INFO] Booting worker with pid: 27016
WARNING
ERROR
[2017-09-20 09:55:08 +0800] [27010] [INFO] Handling signal: term
[2017-09-20 09:55:08 +0800] [27013] [INFO] Worker exiting (pid: 27013)
[2017-09-20 09:55:08 +0800] [27014] [INFO] Worker exiting (pid: 27014)
[2017-09-20 09:55:09 +0800] [27015] [INFO] Worker exiting (pid: 27015)
[2017-09-20 09:55:09 +0800] [27016] [INFO] Worker exiting (pid: 27016)
[2017-09-20 09:55:09 +0800] [27010] [INFO] Shutting down: Master
[2017-09-20 09:55:09 +0800] [29671] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:55:09 +0800] [29671] [INFO] Listening at: http://127.0.0.1:8082 (29671)
[2017-09-20 09:55:09 +0800] [29671] [INFO] Using worker: gevent
[2017-09-20 09:55:09 +0800] [29674] [INFO] Booting worker with pid: 29674
[2017-09-20 09:55:09 +0800] [29675] [INFO] Booting worker with pid: 29675
[2017-09-20 09:55:09 +0800] [29676] [INFO] Booting worker with pid: 29676
[2017-09-20 09:55:09 +0800] [29677] [INFO] Booting worker with pid: 29677
INFO|2017-09-20 09:55:21|29677|140015721646992|server.py:30|INFO
WARNING|2017-09-20 09:55:21|29677|140015721646992|server.py:31|WARNING
ERROR|2017-09-20 09:55:21|29677|140015721646992|server.py:32|ERROR
INFO|2017-09-20 09:55:22|29677|140015721646992|server.py:43|Send successfully!
INFO|2017-09-20 09:55:37|29676|140015721646992|server.py:30|INFO
WARNING|2017-09-20 09:55:37|29676|140015721646992|server.py:31|WARNING
ERROR|2017-09-20 09:55:37|29676|140015721646992|server.py:32|ERROR
INFO|2017-09-20 09:55:38|29676|140015721646992|server.py:43|Send successfully!
[2017-09-20 09:57:36 +0800] [29671] [INFO] Handling signal: term
[2017-09-20 09:57:36 +0800] [29676] [INFO] Worker exiting (pid: 29676)
[2017-09-20 09:57:36 +0800] [29677] [INFO] Worker exiting (pid: 29677)
[2017-09-20 09:57:37 +0800] [29675] [INFO] Worker exiting (pid: 29675)
[2017-09-20 09:57:37 +0800] [29674] [INFO] Worker exiting (pid: 29674)
[2017-09-20 09:57:37 +0800] [29671] [INFO] Shutting down: Master
[2017-09-20 09:57:37 +0800] [30405] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:57:37 +0800] [30405] [INFO] Listening at: http://127.0.0.1:8082 (30405)
[2017-09-20 09:57:37 +0800] [30405] [INFO] Using worker: gevent
[2017-09-20 09:57:37 +0800] [30408] [INFO] Booting worker with pid: 30408
[2017-09-20 09:57:37 +0800] [30409] [INFO] Booting worker with pid: 30409
[2017-09-20 09:57:37 +0800] [30410] [INFO] Booting worker with pid: 30410
[2017-09-20 09:57:37 +0800] [30411] [INFO] Booting worker with pid: 30411
[2017-09-20 09:57:38 +0800] [30408] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:38 +0800] [30408] [INFO] Worker exiting (pid: 30408)
[2017-09-20 09:57:38 +0800] [30409] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:38 +0800] [30409] [INFO] Worker exiting (pid: 30409)
[2017-09-20 09:57:38 +0800] [30410] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:38 +0800] [30410] [INFO] Worker exiting (pid: 30410)
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jumpserver/python3/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2017-09-20 09:57:38 +0800] [30411] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:38 +0800] [30411] [INFO] Worker exiting (pid: 30411)
[2017-09-20 09:57:39 +0800] [30416] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:57:39 +0800] [30416] [INFO] Listening at: http://127.0.0.1:8082 (30416)
[2017-09-20 09:57:39 +0800] [30416] [INFO] Using worker: gevent
[2017-09-20 09:57:39 +0800] [30419] [INFO] Booting worker with pid: 30419
[2017-09-20 09:57:39 +0800] [30420] [INFO] Booting worker with pid: 30420
[2017-09-20 09:57:39 +0800] [30421] [INFO] Booting worker with pid: 30421
[2017-09-20 09:57:39 +0800] [30422] [INFO] Booting worker with pid: 30422
[2017-09-20 09:57:40 +0800] [30419] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:40 +0800] [30419] [INFO] Worker exiting (pid: 30419)
[2017-09-20 09:57:40 +0800] [30420] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:40 +0800] [30420] [INFO] Worker exiting (pid: 30420)
[2017-09-20 09:57:40 +0800] [30421] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:40 +0800] [30421] [INFO] Worker exiting (pid: 30421)
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jumpserver/python3/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2017-09-20 09:57:40 +0800] [30422] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:40 +0800] [30422] [INFO] Worker exiting (pid: 30422)
[2017-09-20 09:57:42 +0800] [30427] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:57:42 +0800] [30427] [INFO] Listening at: http://127.0.0.1:8082 (30427)
[2017-09-20 09:57:42 +0800] [30427] [INFO] Using worker: gevent
[2017-09-20 09:57:42 +0800] [30430] [INFO] Booting worker with pid: 30430
[2017-09-20 09:57:42 +0800] [30431] [INFO] Booting worker with pid: 30431
[2017-09-20 09:57:42 +0800] [30432] [INFO] Booting worker with pid: 30432
[2017-09-20 09:57:42 +0800] [30433] [INFO] Booting worker with pid: 30433
[2017-09-20 09:57:43 +0800] [30430] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:43 +0800] [30430] [INFO] Worker exiting (pid: 30430)
[2017-09-20 09:57:43 +0800] [30431] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:43 +0800] [30431] [INFO] Worker exiting (pid: 30431)
[2017-09-20 09:57:43 +0800] [30432] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:43 +0800] [30432] [INFO] Worker exiting (pid: 30432)
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jumpserver/python3/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2017-09-20 09:57:43 +0800] [30433] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:43 +0800] [30433] [INFO] Worker exiting (pid: 30433)
[2017-09-20 09:57:46 +0800] [30441] [INFO] Starting gunicorn 19.7.1
[2017-09-20 09:57:46 +0800] [30441] [INFO] Listening at: http://127.0.0.1:8082 (30441)
[2017-09-20 09:57:46 +0800] [30441] [INFO] Using worker: gevent
[2017-09-20 09:57:46 +0800] [30444] [INFO] Booting worker with pid: 30444
[2017-09-20 09:57:46 +0800] [30445] [INFO] Booting worker with pid: 30445
[2017-09-20 09:57:46 +0800] [30446] [INFO] Booting worker with pid: 30446
[2017-09-20 09:57:46 +0800] [30447] [INFO] Booting worker with pid: 30447
[2017-09-20 09:57:47 +0800] [30444] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:47 +0800] [30444] [INFO] Worker exiting (pid: 30444)
[2017-09-20 09:57:47 +0800] [30445] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:47 +0800] [30445] [INFO] Worker exiting (pid: 30445)
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jumpserver/python3/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2017-09-20 09:57:47 +0800] [30446] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:47 +0800] [30446] [INFO] Worker exiting (pid: 30446)
[2017-09-20 09:57:47 +0800] [30447] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumpserver/python3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/jumpserver/sender/bin/server.py", line 10, in <module>
    from views.send_mail import Sender
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 4, in <module>
    from ..logger import create_logger
ValueError: attempted relative import beyond top-level package
[2017-09-20 09:57:47 +0800] [30447] [INFO] Worker exiting (pid: 30447)
[2017-09-20 10:20:16 +0800] [3937] [INFO] Starting gunicorn 19.7.1
[2017-09-20 10:20:16 +0800] [3937] [INFO] Listening at: http://127.0.0.1:8082 (3937)
[2017-09-20 10:20:16 +0800] [3937] [INFO] Using worker: gevent
[2017-09-20 10:20:16 +0800] [3940] [INFO] Booting worker with pid: 3940
[2017-09-20 10:20:16 +0800] [3941] [INFO] Booting worker with pid: 3941
[2017-09-20 10:20:16 +0800] [3942] [INFO] Booting worker with pid: 3942
[2017-09-20 10:20:16 +0800] [3943] [INFO] Booting worker with pid: 3943
INFO|2017-09-20 10:20:23|3942|140319413066488|server.py:31|INFO
WARNING|2017-09-20 10:20:23|3942|140319413066488|server.py:32|WARNING
ERROR|2017-09-20 10:20:23|3942|140319413066488|server.py:33|ERROR
Traceback (most recent call last):
  File "/home/jumpserver/sender/bin/server.py", line 43, in main
    sender.send(subject, content, receiver)
  File "/home/jumpserver/sender/bin/views/send_mail.py", line 27, in send
    log.info("Hi {0}".format(content))
NameError: name 'log' is not defined
ERROR|2017-09-20 10:20:23|3942|140319413066488|server.py:46|None
[2017-09-20 10:21:29 +0800] [3937] [INFO] Handling signal: term
[2017-09-20 10:21:30 +0800] [3940] [INFO] Worker exiting (pid: 3940)
[2017-09-20 10:21:30 +0800] [3941] [INFO] Worker exiting (pid: 3941)
[2017-09-20 10:21:30 +0800] [3942] [INFO] Worker exiting (pid: 3942)
[2017-09-20 10:21:30 +0800] [3943] [INFO] Worker exiting (pid: 3943)
[2017-09-20 10:21:30 +0800] [3937] [INFO] Shutting down: Master
[2017-09-20 10:23:52 +0800] [4340] [INFO] Starting gunicorn 19.7.1
[2017-09-20 10:23:52 +0800] [4340] [ERROR] Connection in use: ('127.0.0.1', 8082)
[2017-09-20 10:23:52 +0800] [4340] [ERROR] Retrying in 1 second.
[2017-09-20 10:23:53 +0800] [4340] [ERROR] Connection in use: ('127.0.0.1', 8082)
[2017-09-20 10:23:53 +0800] [4340] [ERROR] Retrying in 1 second.
[2017-09-20 10:23:54 +0800] [4340] [ERROR] Connection in use: ('127.0.0.1', 8082)
[2017-09-20 10:23:54 +0800] [4340] [ERROR] Retrying in 1 second.
[2017-09-20 10:23:55 +0800] [4340] [ERROR] Connection in use: ('127.0.0.1', 8082)
[2017-09-20 10:23:55 +0800] [4340] [ERROR] Retrying in 1 second.
[2017-09-20 10:23:56 +0800] [4340] [INFO] Listening at: http://127.0.0.1:8082 (4340)
[2017-09-20 10:23:56 +0800] [4340] [INFO] Using worker: gevent
[2017-09-20 10:23:56 +0800] [4347] [INFO] Booting worker with pid: 4347
[2017-09-20 10:23:56 +0800] [4348] [INFO] Booting worker with pid: 4348
[2017-09-20 10:23:57 +0800] [4349] [INFO] Booting worker with pid: 4349
[2017-09-20 10:23:57 +0800] [4350] [INFO] Booting worker with pid: 4350
INFO|2017-09-20 10:24:04|4349|140364403071736|server.py:31|INFO
WARNING|2017-09-20 10:24:04|4349|140364403071736|server.py:32|WARNING
ERROR|2017-09-20 10:24:04|4349|140364403071736|server.py:33|ERROR
INFO|2017-09-20 10:24:05|4349|140364403071736|send_mail.py:27|Hi 你好吗
INFO|2017-09-20 10:24:05|4349|140364403071736|server.py:44|Send successfully!
[2017-09-20 10:38:51 +0800] [4340] [INFO] Handling signal: term
[2017-09-20 10:38:51 +0800] [4348] [INFO] Worker exiting (pid: 4348)
[2017-09-20 10:38:51 +0800] [4350] [INFO] Worker exiting (pid: 4350)
[2017-09-20 10:38:51 +0800] [4349] [INFO] Worker exiting (pid: 4349)
[2017-09-20 10:38:52 +0800] [4347] [INFO] Worker exiting (pid: 4347)
[2017-09-20 10:38:52 +0800] [4340] [INFO] Shutting down: Master
[2017-09-20 10:38:53 +0800] [9054] [INFO] Starting gunicorn 19.7.1
[2017-09-20 10:38:53 +0800] [9054] [INFO] Listening at: http://127.0.0.1:8082 (9054)
[2017-09-20 10:38:53 +0800] [9054] [INFO] Using worker: gevent
[2017-09-20 10:38:53 +0800] [9057] [INFO] Booting worker with pid: 9057
[2017-09-20 10:38:53 +0800] [9058] [INFO] Booting worker with pid: 9058
[2017-09-20 10:38:53 +0800] [9059] [INFO] Booting worker with pid: 9059
[2017-09-20 10:38:53 +0800] [9060] [INFO] Booting worker with pid: 9060
2017-09-20 10:39:09 9059,DummyThread-1 server.py:31 [INFO] INFO
2017-09-20 10:39:09 9059,DummyThread-1 server.py:32 [WARNING] WARNING
2017-09-20 10:39:09 9059,DummyThread-1 server.py:33 [ERROR] ERROR
2017-09-20 10:39:10 9059,DummyThread-1 send_mail.py:27 [INFO] Hi 你好吗
2017-09-20 10:39:10 9059,DummyThread-1 server.py:44 [INFO] Send successfully!
[2017-09-20 11:31:45 +0800] [9054] [INFO] Handling signal: term
[2017-09-20 11:31:45 +0800] [9060] [INFO] Worker exiting (pid: 9060)
[2017-09-20 11:31:45 +0800] [9057] [INFO] Worker exiting (pid: 9057)
[2017-09-20 11:31:45 +0800] [9058] [INFO] Worker exiting (pid: 9058)
[2017-09-20 11:31:45 +0800] [9059] [INFO] Worker exiting (pid: 9059)
[2017-09-20 11:31:45 +0800] [9054] [INFO] Shutting down: Master
[2017-09-20 11:31:46 +0800] [27888] [INFO] Starting gunicorn 19.7.1
[2017-09-20 11:31:46 +0800] [27888] [INFO] Listening at: http://127.0.0.1:8082 (27888)
[2017-09-20 11:31:46 +0800] [27888] [INFO] Using worker: gevent
[2017-09-20 11:31:46 +0800] [27891] [INFO] Booting worker with pid: 27891
[2017-09-20 11:31:46 +0800] [27892] [INFO] Booting worker with pid: 27892
[2017-09-20 11:31:46 +0800] [27893] [INFO] Booting worker with pid: 27893
[2017-09-20 11:31:46 +0800] [27894] [INFO] Booting worker with pid: 27894
INFO|2017-09-20 11:31:56|27894|140371959887264|server.py:35|INFO
WARNING|2017-09-20 11:31:56|27894|140371959887264|server.py:36|WARNING
ERROR|2017-09-20 11:31:56|27894|140371959887264|server.py:37|ERROR
INFO|2017-09-20 11:31:57|27894|140371959887264|send_mail.py:29|Hi 你好吗
INFO|2017-09-20 11:31:57|27894|140371959887264|server.py:48|Send successfully!
[2017-09-20 14:49:00 +0800] [27888] [INFO] Handling signal: term
[2017-09-20 14:49:00 +0800] [27892] [INFO] Worker exiting (pid: 27892)
[2017-09-20 14:49:00 +0800] [27893] [INFO] Worker exiting (pid: 27893)
[2017-09-20 14:49:00 +0800] [27894] [INFO] Worker exiting (pid: 27894)
[2017-09-20 14:49:01 +0800] [27891] [INFO] Worker exiting (pid: 27891)
[2017-09-20 14:49:01 +0800] [27888] [INFO] Shutting down: Master
[2017-09-20 14:49:01 +0800] [25314] [INFO] Starting gunicorn 19.7.1
[2017-09-20 14:49:01 +0800] [25314] [INFO] Listening at: http://127.0.0.1:8082 (25314)
[2017-09-20 14:49:01 +0800] [25314] [INFO] Using worker: gevent
[2017-09-20 14:49:01 +0800] [25377] [INFO] Booting worker with pid: 25377
[2017-09-20 14:49:01 +0800] [25378] [INFO] Booting worker with pid: 25378
[2017-09-20 14:49:01 +0800] [25379] [INFO] Booting worker with pid: 25379
[2017-09-20 14:49:01 +0800] [25380] [INFO] Booting worker with pid: 25380
INFO|2017-09-20 14:49:02|25377|140259705932840|server.py:22|Initial, hahah
INFO|2017-09-20 14:49:02|25378|140259705932840|server.py:22|Initial, hahah
INFO|2017-09-20 14:49:02|25379|140259705932840|server.py:22|Initial, hahah
INFO|2017-09-20 14:49:02|25380|140259705932840|server.py:22|Initial, hahah
[2017-09-20 15:36:23 +0800] [25314] [INFO] Handling signal: term
[2017-09-20 15:36:24 +0800] [25377] [INFO] Worker exiting (pid: 25377)
[2017-09-20 15:36:24 +0800] [25378] [INFO] Worker exiting (pid: 25378)
[2017-09-20 15:36:24 +0800] [25379] [INFO] Worker exiting (pid: 25379)
[2017-09-20 15:36:24 +0800] [25380] [INFO] Worker exiting (pid: 25380)
[2017-09-20 15:36:24 +0800] [25314] [INFO] Shutting down: Master
[2017-09-20 15:55:27 +0800] [3250] [INFO] Starting gunicorn 19.7.1
[2017-09-20 15:55:27 +0800] [3250] [INFO] Listening at: http://127.0.0.1:8082 (3250)
[2017-09-20 15:55:27 +0800] [3250] [INFO] Using worker: gevent
[2017-09-20 15:55:27 +0800] [3253] [INFO] Booting worker with pid: 3253
[2017-09-20 15:55:27 +0800] [3254] [INFO] Booting worker with pid: 3254
[2017-09-20 15:55:27 +0800] [3255] [INFO] Booting worker with pid: 3255
[2017-09-20 15:55:27 +0800] [3256] [INFO] Booting worker with pid: 3256
INFO|2017-09-20 15:55:27|3253|139988260289576|server.py:22|Initial, hahah
INFO|2017-09-20 15:55:27|3254|139988260289576|server.py:22|Initial, hahah
INFO|2017-09-20 15:55:27|3255|139988260289576|server.py:22|Initial, hahah
INFO|2017-09-20 15:55:27|3256|139988260289576|server.py:22|Initial, hahah
[2017-09-20 15:55:58 +0800] [3250] [INFO] Handling signal: int
[2017-09-20 15:55:58 +0800] [3254] [INFO] Worker exiting (pid: 3254)
[2017-09-20 15:55:58 +0800] [3256] [INFO] Worker exiting (pid: 3256)
[2017-09-20 15:55:58 +0800] [3255] [INFO] Worker exiting (pid: 3255)
[2017-09-20 15:55:58 +0800] [3253] [INFO] Worker exiting (pid: 3253)
[2017-09-20 15:55:58 +0800] [3250] [INFO] Shutting down: Master
[2017-09-20 16:11:34 +0800] [5494] [INFO] Starting gunicorn 19.7.1
[2017-09-20 16:11:34 +0800] [5494] [INFO] Listening at: http://127.0.0.1:8082 (5494)
[2017-09-20 16:11:34 +0800] [5494] [INFO] Using worker: gevent
[2017-09-20 16:11:34 +0800] [5497] [INFO] Booting worker with pid: 5497
[2017-09-20 16:11:34 +0800] [5498] [INFO] Booting worker with pid: 5498
[2017-09-20 16:11:34 +0800] [5499] [INFO] Booting worker with pid: 5499
[2017-09-20 16:11:34 +0800] [5500] [INFO] Booting worker with pid: 5500
INFO|2017-09-20 16:11:51|5500|139677210699168|api.py:20|INFO
WARNING|2017-09-20 16:11:51|5500|139677210699168|api.py:21|WARNING
ERROR|2017-09-20 16:11:51|5500|139677210699168|api.py:22|ERROR
Traceback (most recent call last):
  File "/home/jumpserver/sender/bin/api.py", line 31, in main
    sender = Sender(app.config["EMAIL_ADDR"], app.config["EMAIL_SERVER"],
NameError: name 'Sender' is not defined
ERROR|2017-09-20 16:11:51|5500|139677210699168|api.py:36|None
[2017-09-20 16:12:58 +0800] [5494] [INFO] Handling signal: term
[2017-09-20 16:12:58 +0800] [5498] [INFO] Worker exiting (pid: 5498)
[2017-09-20 16:12:58 +0800] [5499] [INFO] Worker exiting (pid: 5499)
[2017-09-20 16:12:58 +0800] [5500] [INFO] Worker exiting (pid: 5500)
[2017-09-20 16:12:58 +0800] [5497] [INFO] Worker exiting (pid: 5497)
[2017-09-20 16:12:59 +0800] [5494] [INFO] Shutting down: Master
